// <auto-generated />
using System;
using MangaRepositoryAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MangaRepositoryAPI.Migrations
{
    [DbContext(typeof(MangaRepoDbContext))]
    partial class MangaRepoDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AuthorManga", b =>
                {
                    b.Property<Guid>("AuthorsAuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MangasMangaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AuthorsAuthorId", "MangasMangaId");

                    b.HasIndex("MangasMangaId");

                    b.ToTable("Write", (string)null);
                });

            modelBuilder.Entity("GenreManga", b =>
                {
                    b.Property<Guid>("GenresGenreId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MangasMangaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("GenresGenreId", "MangasMangaId");

                    b.HasIndex("MangasMangaId");

                    b.ToTable("Belong", (string)null);
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Author", b =>
                {
                    b.Property<Guid>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Genre", b =>
                {
                    b.Property<Guid>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GenreName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Manga", b =>
                {
                    b.Property<Guid>("MangaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("ChapterNumber")
                        .HasColumnType("int");

                    b.Property<DateOnly>("PublicationDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MangaId");

                    b.ToTable("Mangas");
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Status", b =>
                {
                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("MangaId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("StatusId");

                    b.HasIndex("MangaId")
                        .IsUnique();

                    b.ToTable("Statuses");
                });

            modelBuilder.Entity("AuthorManga", b =>
                {
                    b.HasOne("MangaRepositoryAPI.Data.Author", null)
                        .WithMany()
                        .HasForeignKey("AuthorsAuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaRepositoryAPI.Data.Manga", null)
                        .WithMany()
                        .HasForeignKey("MangasMangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GenreManga", b =>
                {
                    b.HasOne("MangaRepositoryAPI.Data.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresGenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MangaRepositoryAPI.Data.Manga", null)
                        .WithMany()
                        .HasForeignKey("MangasMangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Status", b =>
                {
                    b.HasOne("MangaRepositoryAPI.Data.Manga", "Manga")
                        .WithOne("Status")
                        .HasForeignKey("MangaRepositoryAPI.Data.Status", "MangaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Manga");
                });

            modelBuilder.Entity("MangaRepositoryAPI.Data.Manga", b =>
                {
                    b.Navigation("Status")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
